### ISSUE TITLE
Need to increase branching_factor?

### ISSUE THREAD

**Issue by rs3793** [mqcomplab/bitbirch#10]
When I used BitBIRCH to cluster ~1 million molecules, it gave the following errors, which seems that the number of sub clusters exceed branching_factor (which was set to be the default value, 50). How should I fix this? Thanks!

Traceback (most recent call last):
  File "/home/bitbirch/bitbirch.py", line 482, in fit
    return self._fit(X)
           ^^^^^^^^^^^^
  File "/home/bitbirch/bitbirch.py", line 523, in _fit
    split = self.root_.insert_bf_subcluster(subcluster, set_bits)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitbirch/bitbirch.py", line 285, in insert_bf_subcluster
    split_child = closest_subcluster.child_.insert_bf_subcluster(subcluster, set_bits)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitbirch/bitbirch.py", line 329, in insert_bf_subcluster
    self.append_subcluster(subcluster)
  File "/home/rui.su/bitbirch.py", line 252, in append_subcluster
    self.init_centroids_[n_samples] = subcluster.centroid_
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
IndexError: index 51 is out of bounds for axis 0 with size 51

**Comment by ramirandaq** [comment]
Are you passing the fingerprints as a numpy array with elements given as int64? If you can share the script you are using to run BitBIRCH that could also be helpful.

**Comment by rs3793** [comment]
I use the same way to get fingerprints as in your Jupyter notebook. Basically 

```
mols = [Chem.MolFromSmiles(x) for x in smiles]
generator = rdFingerprintGenerator.GetMorganGenerator(radius=3, fpSize=2048)
fps = np.array([generator.GetCountFingerprintAsNumPy(mol) for mol in mols])
bb = BitBirch(threshold=0.65, branching_factor=50)
bb.fit(fps)
```

There is no duplicates in smiles (but two smiles may have the same fingerprint). In my example, fps.dtype='uint32'

**Comment by ramirandaq** [comment]
Try changing the fps.dtype to 'int64'

**Comment by ramirandaq** [comment]
OK, that might be a cause as well. Since we are usually handling ~100s of millions of compounds, to be on the safer side we prefer running all calculations with int64 (BitBIRCH is still memory-efficient enough that this is not going to be a problem, and we even run most of the calculations on regular laptops). I'd be wary of uint8, be aware that it might fail once you go to bigger datasets. Overall, a branching factor of 50 will work in all cases, so the type of error you were seeing is most likely associated to some issue with the fps. Let us know if everything looks good once you curate the fps.
