### ISSUE TITLE
Incorrect docstring for the BitBirch.get_centroids function

### ISSUE THREAD

**Issue by nickholway** [mqcomplab/bitbirch#5]
The [docstring for get_centroids](https://github.com/mqcomplab/bitbirch/blob/f43a6a492f39fef4db8c00b4f638e2bd43408f3f/bitbirch.py#L565C1-L565C72) says "Method to return the indices of molecules in each cluster" whereas the actual code returns a list of Numpy arrays containing the fingerprints.

**Comment by TienMPhan** [comment]
Hi, is there an easy way to get the indices of the centroid molecules?

**Comment by ramirandaq** [comment]
Hi @nickholway, thanks for checking this! We'll go through the code right away and incorporate the changes.
@TienMPhan, there are no indices for the centroids, since they don't necessarily correspond to "real" molecules (they are not "medoids"). A potential way to get representative structures from the BitBIRCH clusters is to run the medoid function in our iSIM module for every cluster of interest, which will retrieve actual molecules in your set.
